services:
  - type: web
    name: velocitymatch-viz
    env: python
    plan: starter  # Adjust to your preferred paid plan
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: "false"
